<?php
/**
 * Created by PhpStorm.
 * User: ii
 * Date: 24.02.16
 * Time: 9:07
 */

namespace broshchak\multlang;

use Illuminate\Support\Facades\Facade;


class MyLanguageFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        //parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'broshchak\multlang\MyLanguageInterface';
    }
}